const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),projectId=params.get("id");let activeFile=null,project=null;
const log=t=>{const c=$("#console");c.textContent+="\n"+t;c.scrollTop=c.scrollHeight};
async function api(path,opts={}){const r=await fetch("/api/"+path,{credentials:"same-origin",...opts});const text=await r.text();let d={};try{d=JSON.parse(text)}catch{d={error:text}}if(r.status===401){location.href="/";throw new Error("Unauthorized")}if(!r.ok)throw new Error(d.error+(d.detail?": "+d.detail:""));return d}
async function loadProject(){const {projects}=await api("projects");project=projects.find(x=>x.id===projectId);if(!project){location.href="/";return}$("#projectTitle").textContent=project.name;$("#projectMeta").textContent=project.type.toUpperCase()+" • "+project.id;$("#status").textContent=project.status;$("#previewBtn").style.display=project.type==="web"?"inline-block":"none";await loadFiles();await refreshLogs()}
async function loadFiles(){const {files}=await api("files?projectId="+encodeURIComponent(projectId));const box=$("#files");box.innerHTML=files.map(f=>`<div class="file ${f===activeFile?"active":""}" data-file="${encodeURIComponent(f)}">${f.replace(/</g,"&lt;")}</div>`).join("");box.querySelectorAll(".file").forEach(el=>el.onclick=()=>openFile(decodeURIComponent(el.dataset.file)));if(!activeFile&&files.length)openFile(files[0])}
async function openFile(path){const d=await api(`files?projectId=${encodeURIComponent(projectId)}&path=${encodeURIComponent(path)}`);activeFile=path;$("#currentFile").textContent=path;$("#editor").disabled=false;$("#editor").value=d.content;await loadFiles()}
async function save(){if(!activeFile)return;await api("files?projectId="+encodeURIComponent(projectId),{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({path:activeFile,content:$("#editor").value})});log("Saved "+activeFile)}
$("#saveBtn").onclick=()=>save().catch(e=>log("ERROR: "+e.message));
$("#newFile").onclick=async()=>{const p=prompt("New file path (example: src/bot.js)");if(!p)return;try{await api("files?projectId="+encodeURIComponent(projectId),{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({path:p,content:""})});activeFile=p;await loadFiles();await openFile(p)}catch(e){alert(e.message)}};
async function run(restart=false){try{await save().catch(()=>{});if(restart)await stop().catch(()=>{});const d=await api("run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId})});log(d.message||"Run requested.");$("#status").textContent=project.type==="web"?"preview":"running";if(project.type==="web")previewWeb();setTimeout(refreshLogs,700)}catch(e){log("ERROR: "+e.message)}}
async function stop(){const d=await api("stop",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId})});log(d.message||"Stop requested.");$("#status").textContent="stopped";return d}
$("#runBtn").onclick=()=>run(false);$("#restartBtn").onclick=()=>run(true);$("#stopBtn").onclick=()=>stop().catch(e=>log("ERROR: "+e.message));
async function refreshLogs(){try{const d=await api("logs?projectId="+encodeURIComponent(projectId));$("#console").textContent=(d.logs||[]).join("\n")||"No logs yet.";if(d.status)$("#status").textContent=d.status}catch(e){log("ERROR: "+e.message)}}
$("#refreshLogs").onclick=refreshLogs;
$("#deleteProject").onclick=async()=>{if(!confirm("Delete this project and all files?"))return;try{await api("projects?id="+encodeURIComponent(projectId),{method:"DELETE"});location.href="/"}catch(e){alert(e.message)}};
async function previewWeb(){try{await save().catch(()=>{});const d=await api(`files?projectId=${encodeURIComponent(projectId)}&path=index.html`);$("#preview").srcdoc=d.content;$("#previewModal").classList.remove("hidden")}catch(e){log("Preview error: "+e.message)}}
$("#previewBtn").onclick=previewWeb;loadProject().catch(e=>log("ERROR: "+e.message));
